version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
    commit-message:
      prefix: "github-actions"
      include: "scope"

updates:
  - package-ecosystem: "pip"
    directory: "/Python"
    schedule:
      interval: "weekly"
      day: "thursday"
    commit-message:
      prefix: "pip prod"
      prefix-development: "pip dev"
      include: "scope"

updates:
  - package-ecosystem: "pip"
    directory: "/visualization"
    schedule:
      interval: "weekly"
      day: "thursday"
    commit-message:
      prefix: "pip prod"
      prefix-development: "pip dev"
      include: "scope"
