name: test

on:
  push:
      branches:
      - ubuntu

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: prepare
      run: |
        echo "deb http://cz.archive.ubuntu.com/ubuntu eoan main universe" | sudo tee -a  /etc/apt/sources.list
        sudo apt update
        sudo apt install libtbb-dev

    - name: configure
      run: |
        git submodule update --init --recursive
        cd Cpp
        mkdir build
        cd build
        cmake ..

    - name: build
      run: |
        cd Cpp/build
        cmake --build . -- -j $(nproc)

    - name: test
      run: |
        export ECOSYSTEM_ROOT=`pwd`
        ./Cpp/build/setup/setup
        ./Cpp/build/RandomTests/rt_sanity_test
        ./Cpp/build/tests/tests
