name: build

on:
  push:
      branches:
      - actions-test

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: prepare
      run: |
        sudo apt update
        sudo apt install libbtbb-dev

    - name: configure
      run: |
        cd Cpp
        mkdir build
        cd build
        cmake ..

    - name: build
      run: |
        cd Cpp/build
        make
