name: build

on:
  push:
      branches:
      - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: prepare
      run: |
        echo "deb http://cz.archive.ubuntu.com/ubuntu eoan main universe" | sudo tee -a  /etc/apt/sources.list
        sudo apt update
        sudo apt install libtbb-dev

    - name: configure
      run: |
        cd Cpp
        mkdir build
        cd build
        cmake ..

    - name: build
      run: |
        cd Cpp/build
        make
