name: build

on:
  push:
      branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: prepare-build
      run: |
        sudo apt update
        sudo apt install libtbb-dev freeglut3-dev libglfw3 libglfw3-dev libglew-dev

    - name: configure-build
      run: |
        cd Cpp
        mkdir build
        cd build
        cmake ..

    - name: build
      run: |
        cd Cpp/build
        cmake --build . -- -j $(nproc)
