name: test

on:
  push:
      branches:
      - master

jobs:
  test-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: prepare
      run: |
        sudo apt update
        sudo apt install libtbb-dev

    - name: configure
      run: |
        git submodule update --init --recursive
        cd Cpp
        mkdir build
        cd build
        cmake ..

    - name: build
      run: |
        cd Cpp/build
        cmake --build . -- -j $(nproc)

    - name: test
      run: |
        ./Cpp/build/setup/setup
        ./Cpp/build/RandomTests/rt_sanity_test
