name: test

on:
  push:
      branches:
      - ubuntu

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: prepare
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 50
        sudo update-alternatives --set gcc "/usr/bin/gcc-9"
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 50
        sudo update-alternatives --set g++ "/usr/bin/g++-9"

    - name: configure
      run: |
        git submodule update --init
        cd Cpp
        mkdir build
        cd build
        cmake ..

    - name: build
      run: |
        cd Cpp/build
        make

    - name: test
      run: |
        export ECOSYSTEM_ROOT=`pwd`
        ./Cpp/build/setup
        ./Cpp/build/rt_sanity_test
        python Python/test.py