name: detox-messages

on: [issue_comment, pull_request_review]

jobs:
  toxic-check:
    runs-on: ubuntu-20.04
    name: Toxicity check
    steps:
      - uses: actions/checkout@v2

      - name: safe-space
        uses: charliegerard/safe-space@master
        with:
          GITHUB_TOKEN: ${{ secrets.DETOX_GITHUB_TOKEN }}
          message: "Please be kind on internet. You'd be surprised how far a little kindness can take you."
          toxicity_threshold: 0.7
