name: firebase-deploy

'on':
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ECOSYSTEM_SIMULATION }}'
          channelId: live
          projectId: ecosystem-simulation
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
