name: python-test

on:
  push:
    branches: 
    - master
    paths:
    - 'Python/**'
    - 'Cpp/**'
  pull_request:
    branches:
    - master
    paths:
    - 'Python/**'
    - 'Cpp/**'

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: prepare-build
      run: |
        sudo apt update
        sudo apt install libtbb-dev freeglut3-dev libglfw3 libglfw3-dev libglew-dev

    - name: configure-build
      run: |
        cd Cpp
        mkdir build
        cd build
        cmake ..

    - name: build
      run: |
        cd Cpp/build
        cmake --build . -- -j $(nproc)

    - name: install-dependencies
      run: |
        cd Python
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run
      run: |
        ./Cpp/build/setup/setup
        cd Python/RandomTests
        python sanity_test.py
