name: generate-report

on:
  push:
      branches:
      - master
  workflow_dispatch:

jobs:
  report-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: prepare
      run: |
        echo "deb http://cz.archive.ubuntu.com/ubuntu eoan main universe" | sudo tee -a  /etc/apt/sources.list
        sudo apt update
        sudo apt install libtbb-dev

    - name: configure
      run: |
        git submodule update --init --recursive
        cd Cpp
        mkdir build
        cd build
        cmake ..

    - name: build
      run: |
        cd Cpp/build
        cmake --build . -- -j $(nproc)

    - name: run-simulation
      run: |
        ./Cpp/build/setup/setup
        ./Cpp/build/RandomTests/rt_reportgen_test

    - name: generate-report
      run: |
        cd visualization
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python simulation_analysis.py -s animal/deer -o ../outputs/new_report.pdf

    - name: upload-report
      uses: actions/upload-artifact@v2
      with:
        name: Simulation Report
        path: outputs/new_report.pdf
